{{- if (and .Values.serviceAccount (default true .Values.serviceAccount.create)) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}