apiVersion: v2
name: alloy
description: Alloy helm chart
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: alloy
    version: 1.2.1
    repository: https://grafana.github.io/helm-charts