alloy:
  revisionHistoryLimit: 2
  serviceAccount:
    create: true
    name: alloy
  rbac:
    create: true
  alloy:
    mounts:
      # Mount /var/log to access pod logs
      varlog: true
    configMap:
      # Use the ConfigMap created before
      create: false
      name: alloy-settings # <<< Point to the ConfigMap
      key: config.alloy
  # IMPORTANT: Set Resource Requests/Limits AFTER evaluating your use case requirements
  resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 400m
    memory: 1Gi

  # Tolerations for pod assignment
  controller:
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - key: "node-role"
        operator: "Exists"
        effect: "NoExecute"