apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-curl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-app
  template:
    metadata:
      labels:
        app: curl-app
    spec:
      nodeSelector:
        node-role.kubernetes.io/log-workloads: ""
      tolerations:
      - key: "node-role"
        operator: "Equal"
        value: "log-workloads"
        effect: "NoExecute"
      containers:
      - name: curl-container
        image: curlimages/curl
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600; done"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"