apiVersion: v2
name: ingress-nginx
description: Ingress Nginx Chart
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: ingress-nginx
    version: 4.13.0
    #4.11.4 #Check for CVEs
    #4.12.3 has a lot of CVE in used nginx 1.25.5
    #4.13.0
    repository: https://kubernetes.github.io/ingress-nginx