apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: curl-pod
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            nginx-ingress: enabled
  template:
    metadata:
      name: 'curl-pod-{{name}}'
    spec:
      project: dex-apps
      sources:
      - repoURL: https://github.com/JJOInvest/dex-apps
        targetRevision: main
        path: apps/curl-pod/
      destination:
        name: '{{name}}'
        namespace: dev-dex
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true