apiVersion: v1
kind: Pod
metadata:
  name: test-image-pull
  namespace: dev-mcops
spec:
  containers:
    - name: test-app
      image: ghcr.io/akup/multicanister/pocket-ic-core:main
      command: ["echo", "Image pulled successfully"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "25m"
        limits:
          memory: "64Mi"
          cpu: "50m"
  imagePullSecrets:
    - name: mcops-registry
  restartPolicy: Never
