apiVersion: v2
name: cert-manager
description: Cert-manager helm chart
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: cert-manager
    version: v1.18.2
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled