apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alloy
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            monitoring: enabled
            loki: enabled
  template:
    metadata:
      name: 'alloy-{{name}}'
    spec:
      project: cluster-addons
      sources:
      - repoURL: https://github.com/akup/multicanister
        targetRevision: main
        path: infra/argocd/mc-cluster-addons/addons/alloy/
        helm:
          releaseName: alloy
          valueFiles:
            - 'values.yaml'
      - repoURL: https://github.com/akup/multicanister
        targetRevision: main
        path: infra/argocd/mc-cluster-addons/addons/alloy/
      destination:
        name: '{{name}}'
        namespace: logging
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PrunePropagationPolicy=foreground
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m