apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            nginx-ingress: enabled
  template:
    metadata:
      name: 'ingress-nginx-{{name}}'
    spec:
      project: cluster-addons
      source:
        repoURL: https://github.com/akup/multicanister
        targetRevision: main
        path: infra/argocd/mc-cluster-addons/addons/ingress-nginx/
        helm:
          releaseName: ingress-nginx
          valueFiles:
            - 'values.yaml'
          # - 'values/{{name}}.yaml' #Cluster specific values file ({{name}} is the cluster name)
      destination:
        name: '{{name}}'
        namespace: ingress
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true