apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stakater-reloader
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            wireguard-gate: enabled
  template:
    metadata:
      name: 'stakater-reloader-{{name}}'
    spec:
      project: cluster-addons
      source:
        repoURL: https://github.com/akup/multicanister
        targetRevision: main
        path: infra/argocd/mc-cluster-addons/addons/stakater-reloader/
        helm:
          releaseName: stakater-reloader
          valueFiles:
            - 'values.yaml'
            # - 'values/{{name}}.yaml' #Cluster specific values file ({{name}} is the cluster name)
      destination:
        name: '{{name}}'
        namespace: security
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true