apiVersion: v2
name: grafana
description: Grafana Chart
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: grafana
    version: 9.3.2
    repository: https://grafana.github.io/helm-charts